<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_orders = $this->getOrders(); ?>



<div class="panel panel-default">
    <div class="panel-body">
        <?php echo $this->getPagerHtml(); ?>
        <?php if($_orders->getSize()): ?>
            <table class="table table-condensed" id="my-orders-table">
                <col width="1" />
                <col width="1" />
                <col />
                <col class="hidden-xs" width="1"/>
                <col class="hidden-xs" width="1" />
                <thead>
                <tr>
                    <th><?php echo $this->__('Order #') ?></th>
                    <th><?php echo $this->__('Date') ?></th>
                    <th class="hidden-xs"><?php echo $this->__('Ship To') ?></th>
                    <th class="hidden-xs"><span class="nobr"><?php echo $this->__('Order Total') ?></span></th>
                    <th style="text-align: right;"><span class="nobr"><?php echo $this->__('Order Status') ?></span></th>
                </tr>
                </thead>
                <tbody>
                <?php $_odd = ''; ?>
                <?php foreach ($_orders as $_order): ?>
                    <tr>
                        <td><a href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $_order->getRealOrderId() ?></a></td>
                        <td><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
                        <td class="hidden-xs"><?php echo $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                        <td class="hidden-xs"><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                        <td style="text-align: right;"><em><?php echo $_order->getStatusLabel() ?></em></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
            <script type="text/javascript">decorateTable('my-orders-table');</script>
            <?php echo $this->getPagerHtml(); ?>
        <?php else: ?>
            <p><?php echo $this->__('You have placed no orders.'); ?></p>
        <?php endif ?>
    </div>
</div>
