<?php echo $this->getMessagesBlock()->toHtml() ?>

<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate" role="form">
    <?php echo $this->getBlockHtml('formkey')?>

    <fieldset>
        <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
        <div class="form-group">
            <label for="email" class="required control-label"><?php echo $this->__('Email Address') ?></label>
            <input type="text"
                   name="email"
                   id="email"
                   value="<?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?>"
                   title="<?php echo $this->__('Email Address') ?>"
                   placeholder="<?php echo $this->__('Email Address') ?>"
                   class="input-text required-entry validate-email form-control" />
        </div>
        <div class="form-group">
            <label for="current_password" class="required control-label"><?php echo Mage::helper('core')->quoteEscape($this->__('Current Password')) ?></label>
            <!-- This is a dummy hidden field to trick firefox from auto filling the password -->
            <input type="text" class="input-text no-display" name="dummy" id="dummy" />
            <input type="password"
                   title="<?php echo Mage::helper('core')->quoteEscape($this->__('Current Password')) ?>"
                   class="input-text required-entry form-control"
                   name="current_password"
                   id="current_password" />
        </div>
        <div class="checkbox">
            <label>
                <input type="checkbox"
                       name="change_password"
                       id="change_password"
                       value="1"
                       onclick="setPasswordForm(this.checked)"
                       title="<?php echo $this->__('Change Password') ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?>/><?php echo $this->__('Change Password') ?>
            </label>
        </div>
    </fieldset>

    <fieldset style="display:none;">
        <h2 class="legend"><?php echo $this->__('Change Password') ?></h2>
        <div class="form-group">
            <label for="password" class="required"><?php echo $this->__('New Password') ?></label>
            <input type="password"
                   title="<?php echo Mage::helper('core')->quoteEscape($this->__('New Password')) ?>"
                   class="input-text required-entry validate-password form-control"
                   name="password"
                   id="password" />
        </div>
        <div class="form-group">
            <label for="confirmation" class="required"><?php echo $this->__('Confirm New Password') ?></label>
            <input type="password"
                   title="<?php echo Mage::helper('core')->quoteEscape($this->__('Confirm New Password')) ?>"
                   class="input-text required-entry validate-cpassword form-control"
                   name="confirmation"
                   id="confirmation" />
        </div>
    </fieldset>

    <div class="buttons-set clearfix">
        <a class="btn btn-default pull-left" href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a>
        <button type="submit"
                title="<?php echo $this->__('Save') ?>"
                class="btn btn-primary pull-right"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>

</form>

<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg){
        $('password').up('fieldset')[arg ? 'show': 'hide']();
    }

    <?php if($this->getCustomer()->getChangePassword()): ?>
    setPasswordForm(true);
    <?php endif; ?>
    //]]>
</script>
