
<div class="form-content-body">

    <div class="page-title">
        <h1><?php echo $this->__('Forgot Your Password?') ?></h1>
    </div>

    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

    <form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">

        <fieldset>
            <h2><?php echo $this->__('Retrieve your password here') ?></h2>
            <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
            <div class="row">
                <div class="form-group col-sm-6">
                    <label for="email_address" class="required control-label"><?php echo $this->__('Email Address') ?></label>
                    <input type="text"
                           name="email"
                           placeholder="<?php echo $this->__('Email Address') ?>"
                           alt="email"
                           id="email_address"
                           class="input-text required-entry validate-email form-control"
                           value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>" />

                    <?php echo $this->getChildHtml('form.additional.info'); ?>
                </div>
            </div>
        </fieldset>

        <div class="buttons-set clearfix">
            <a class="pull-left btn btn-default" href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a>
            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="btn btn-primary pull-right"><span><span><?php echo $this->__('Submit') ?></span></span></button>
        </div>
    </form>
</div>

<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    //]]>
</script>
