
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('form_before')?>
<form action="<?php echo $this->getAction() ?>" method="post" id="form-validate">
    <fieldset>
        <?php echo $this->getBlockHtml('formkey')?>
        <h2><?php echo $this->__('Newsletter Subscription') ?></h2>
        <div class="checkbox">
            <label for="subscription" class="control-label">
                <input type="checkbox"
                       name="is_subscribed"
                       id="subscription"
                       value="1"
                       title="<?php echo $this->__('General Subscription') ?>"
                       <?php if($this->getIsSubscribed()): ?>checked="checked"<?php endif; ?>
                       class="checkbox" /><?php echo $this->__('General Subscription') ?>
            </label>
        </div>
        <?php /* Extensions placeholder */ ?>
        <?php echo $this->getChildHtml('customer.form.newsletter.extra')?>
    </fieldset>
    <div class="buttons-set clearfix">
        <a class="btn btn-default pull-left" href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="btn btn-default pull-right"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
</form>
<?php /* Extensions placeholder */ ?>
<?php echo $this->getChildHtml('customer.form.newsletter.extra2')?>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    //]]>
</script>
