
<div class="form-content-body">

    <div class="page-title">
        <h1><?php echo $this->__('Reset a Password'); ?></h1>
    </div>

    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

    <form action="<?php echo $this->getUrl('*/*/resetpasswordpost', array('_query' => array('id' => $this->getCustomerId(), 'token' => $this->getResetPasswordLinkToken()))); ?>" method="post" id="form-validate">
        <fieldset>
            <div class="form-group">
                <label for="password" class="required control-label"><?php echo $this->__('New Password'); ?></label>
                <input type="password"
                       name="password"
                       class="input-text required-entry validate-password form-control"
                       placeholder="<?php echo $this->__('New Password'); ?>"
                       id="password" />
            </div>
            <div class="form-group">
                <label for="confirmation" class="required"><?php echo $this->__('Confirm New Password'); ?></label>
                <input type="password"
                       class="input-text required-entry validate-cpassword form-control"
                       name="confirmation"
                       placeholder="<?php echo $this->__('Confirm New Password'); ?>"
                       id="confirmation" />
            </div>
        </fieldset>
        <div class="buttons-set">
            <button type="submit" title="<?php echo $this->__('Reset a Password'); ?>" class="btn btn-primary"><span><span><?php echo $this->__('Reset a Password'); ?></span></span></button>
        </div>
    </form>
</div>

<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    //]]>
</script>
