
<script type="text/javascript">
    //<![CDATA[
    var quoteBaseGrandTotal = <?php echo (float)$this->getQuoteBaseGrandTotal(); ?>;
    var checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
    var payment = new Payment('co-payment-form', '<?php echo $this->getUrl('checkout/onepage/savePayment') ?>');
    var lastPrice;
    //]]>
</script>

<fieldset>
    <form action="" id="co-payment-form">
        <div class="step-title"><h3><?php echo $this->__('Payment Method') ?></h3></div>
        <?php echo $this->getChildHtml('methods') ?>
    </form>
    <div class="buttons-set" id="payment-buttons-container">
        <a href="#" class="btn btn-default" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a>
        <button type="button" class="btn btn-primary" onclick="payment.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span class="please-wait" id="payment-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" />
        </span>
    </div>
</fieldset>


<script type="text/javascript">
    //<![CDATA[
    function toggleToolTip(event){
        if($('payment-tool-tip')){
            $('payment-tool-tip').setStyle({
                top: (Event.pointerY(event)-560)+'px'//,
                //left: (Event.pointerX(event)+100)+'px'
            })
            $('payment-tool-tip').toggle();
        }
        Event.stop(event);
    }
    if($('payment-tool-tip-close')){
        Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
    }
    //]]>
</script>
<script type="text/javascript">
    //<![CDATA[
    payment.currentMethod = "<?php echo $this->getChild('methods')->getSelectedMethodCode() ?>";
    //]]>
</script>
