
<form id="co-shipping-method-form" action="">
    <fieldset>
        <div class="step-title"><h3><?php echo $this->__('Shipping Method') ?></h3></div>
        <div id="checkout-shipping-method-load">
            <!-- Content loaded dynamically -->
        </div>
        <script type="text/javascript">
            //<![CDATA[
            var shippingMethod = new ShippingMethod('co-shipping-method-form', "<?php echo $this->getUrl('checkout/onepage/saveShippingMethod') ?>");
            //]]>
        </script>
        <div id="onepage-checkout-shipping-method-additional-load">
            <?php echo $this->getChildHtml('additional') ?>
        </div>
        <div class="buttons-set" id="shipping-method-buttons-container">
            <a href="#" class="btn btn-default"  onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a>
            <button type="button" class="btn btn-primary" onclick="shippingMethod.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
            <span id="shipping-method-please-wait" class="please-wait" style="display:none;">
                <img src="<?php echo $this->getSkinUrl('images/ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" />
            </span>
        </div>
    </fieldset>
</form>
