
<?php echo $this->getChildHtml('login_before')?>

<fieldset>
    <h2><?php echo $this->__('Checkout as a Guest or Register') ?></h2>
    <p><?php echo $this->__('Register with us for future convenience:') ?></p>
    <ul class="form-list">
        <li class="control radio">
            <label for="login:guest">
                <input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_GUEST): ?> checked="checked"<?php endif; ?> class="radio" />
                <?php echo $this->__('Checkout as Guest') ?>
            </label>
        </li>
        <li class="control radio">
            <label for="login:register">
                <input type="radio" name="checkout_method" id="login:register" value="register"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> class="radio" />
                <?php echo $this->__('Register') ?>
            </label>
        </li>
    </ul>
    <!--div class="form-static">
        <h4><?php echo $this->__('Register and save time!') ?></h4>
        <p><?php echo $this->__('Register with us for future convenience:') ?></p>
        <ul>
            <li><?php echo $this->__('Fast and easy check out'); ?></li>
            <li><?php echo $this->__('Easy access to your order history and status'); ?></li>
        </ul>
    </div-->
    <div class="buttons-set">
        <button id="onepage-guest-register-button" type="button" class="btn btn-primary" onclick="checkout.setMethod();"><span><span><?php echo $this->__('Continue') ?></span></span></button>
    </div>
</fieldset>

<fieldset>
    <h2><?php echo $this->__('Login') ?></h2>

    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

    <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post" role="form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <p><?php echo $this->__('Already registered?') ?> <?php echo $this->__('Please log in below:') ?></p>

        <div class="row">
            <div class="form-group col-lg-9">
                <label for="login-email" class="required control-label"><?php echo $this->__('Email Address') ?></label>
                <input type="text" class="form-control required-entry validate-email" id="login-email" name="login[username]" placeholder="<?php echo $this->__('Email Address') ?>" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" />
            </div>
        </div>
        <div class="row">
            <div class="form-group col-lg-9">
                <label for="login-password" class="required control-label"><?php echo $this->__('Password') ?></label>
                <input type="password" class="form-control required-entry" id="login-password" name="login[password]" placeholder="<?php echo $this->__('Password') ?>" />
            </div>
        </div>

        <?php echo $this->getChildHtml('form.additional.info'); ?>
        <?php echo $this->getChildHtml('persistent.remember.me'); ?>
        <input name="context" type="hidden" value="checkout" />

        <div class="buttons-set">
            <button type="submit" class="btn btn-primary" onclick="onepageLogin(this)"><?php echo $this->__('Login') ?></button>
        </div>
        <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" ><?php echo $this->__('Forgot your password?') ?></a>

    </form>
</fieldset>




<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(button)
    {
        if(loginForm.validator && loginForm.validator.validate()){
            button.disabled = true;
            loginForm.submit();
        }
    }
//]]>
</script>
<?php
    $registerParam = $this->getRequest()->getParam('register');
    if ($registerParam || $registerParam === ''):
?>
    <script type="text/javascript">
    //<![CDATA[
        document.observe("dom:loaded", function() {
            if($('login:register')) {
                $('login:register').checked = true;
                checkout.setMethod();
            }
        })
    //]]>
    </script>
<?php endif; ?>
