<footer>
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="footer-logo-box ">
                    <a href="https://kbh-skum.dk" title="Til forsiden" class="logo"><img src="<?php echo $this->getSkinUrl('images/logo.png')?>" alt="Kbh-Skum ApS" /></a>
                    <p><i class="glyphicon glyphicon-earphone"></i> 71 99 70 90 - Hverdage kl. 10:00-16:00</p>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="footer-address-box">
                    <address>
                        <strong>KBH SKUM ApS</strong><br>
                        CVR: 31 86 37 32<br>
                        Roskildevej 332A<br>
                        2670 Tåstrup
                    </address>
                </div>
            </div>
        </div>
    </div>
</footer>