
<div class="account-login container fontscale">
    <div class="form-content-body">

        <div class="page-title">
            <h1><?php echo $this->__('Login or Create an Account') ?></h1>
        </div>

        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

        <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form" role="form">
            <fieldset>
                <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />

                <div class="row">

                    <div class="new-users col-sm-6">
                        <h2><?php echo $this->__('New Customers') ?></h2>
                        <p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
                        <div class="buttons-set">
                            <button type="button" title="<?php echo $this->__('Create an Account') ?>" class="button btn btn-primary" onclick="window.location='<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>';"><span><span><?php echo $this->__('Create an Account') ?></span></span></button>
                        </div>
                    </div>
                    <div class="registered-users col-sm-6 ">
                        <h2><?php echo $this->__('Registered Customers') ?></h2>
                        <p><?php echo $this->__('If you have an account with us, please log in.') ?></p>

                        <div class="form-group">
                            <label for="email" class="required control-label"><?php echo $this->__('Email Address') ?></label>
                            <input type="text"
                                   name="login[username]"
                                   value="<?php echo $this->htmlEscape($this->getUsername()) ?>"
                                   id="email"
                                   class="input-text required-entry validate-email form-control"
                                   placeholder="<?php echo $this->__('Email Address') ?>"
                                   title="<?php echo $this->__('Email Address') ?>" />
                        </div>
                        <div class="form-group">
                            <label for="pass" class="required control-label"><?php echo $this->__('Password') ?></label>
                            <input type="password"
                                   name="login[password]"
                                   class="input-text required-entry validate-password form-control"
                                   id="pass"
                                   placeholder="<?php echo $this->__('Password') ?>"
                                   title="<?php echo $this->__('Password') ?>" />
                        </div>

                        <a href="<?php echo $this->getForgotPasswordUrl() ?>" class=""><?php echo $this->__('Opret nyt password') ?></a>&nbsp;/&nbsp;<a href="<?php echo $this->getForgotPasswordUrl() ?>" class=""><?php echo $this->__('Forgot Your Password') ?></a>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                        <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                        <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                        <div class="buttons-set">
                            <button type="submit" class="button btn btn-default" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
                        </div>
                    </div>
                </div>
                <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
                    <input name="context" type="hidden" value="checkout" />
                <?php endif; ?>
            </fieldset>
        </form>

    </div>
</div>

<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('login-form');
    //]]>
</script>
