<div class="container account-create fontscale">
    <div class="form-content-body">

        <div class="page-title">
            <h1><?php echo $this->__('Create an Account') ?></h1>
        </div>
        <?php echo $this->getChildHtml('form_fields_before')?>

        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

        <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
            <fieldset>
                <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                <div class="form-group">
                    <label for="email_address" class="required control-label"><?php echo $this->__('Email Address') ?></label>
                    <input type="text"
                           name="email"
                           id="email_address"
                           value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>"
                           title="<?php echo $this->__('Email Address') ?>"
                           placeholder="<?php echo $this->__('Email Address') ?>"
                           class="input-text form-control validate-email required-entry" />
                </div>
                <?php if ($this->isNewsletterEnabled()): ?>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?>  />
                            <?php echo $this->__('Sign Up for Newsletter') ?>
                        </label>
                    </div>
                <?php endif ?>

                <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                <?php if ($_dob->isEnabled()): ?>
                    <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
                <?php endif ?>
                <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                <?php if ($_taxvat->isEnabled()): ?>
                    <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
                <?php endif ?>
                <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                <?php if ($_gender->isEnabled()): ?>
                    <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
                <?php endif ?>
            </fieldset>
            <fieldset>
                <div class="form-group">
                    <label for="password" class="required control-label"><?php echo $this->__('Password') ?></label>
                    <input type="password"
                           name="password"
                           id="password"
                           title="<?php echo $this->__('Password') ?>"
                           placeholder="<?php echo $this->__('Password') ?>"
                           class="input-text form-control required-entry validate-password" />
                </div>

                <div class="form-group">
                    <label for="confirmation" class="required control-label"><?php echo $this->__('Confirm Password') ?></label>
                    <input type="password"
                           name="confirmation"
                           title="<?php echo $this->__('Confirm Password') ?>"
                           placeholder="<?php echo $this->__('Confirm Password') ?>"
                           id="confirmation"
                           class="input-text form-control required-entry validate-cpassword" />
                </div>

                <?php echo $this->getChildHtml('form.additional.info'); ?>
                <?php echo $this->getChildHtml('persistent.remember.me'); ?>
            </fieldset>
            <div class="buttons-set clearfix">
                <a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="btn btn-default pull-left"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
                <button type="submit" title="<?php echo $this->__('Submit') ?>" class="btn btn-primary pull-right"><span><span><?php echo $this->__('Submit') ?></span></span></button>
            </div>
            <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
                <input name="context" type="hidden" value="checkout" />
            <?php endif; ?>

        </form>
    </div>
</div>

<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    <?php if($this->getShowAddressFields()): ?>
    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
    <?php endif; ?>
    //]]>
</script>
