
<div class="panel panel-default">
    <div class="panel-heading">
        <a href="<?php echo $this->getUrl('customer/account/edit') ?>"
           title="<?php echo $this->__('Edit') ?> <?php echo $this->__('Contact Information') ?>">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <?php echo $this->__('Contact Information') ?>
        </a>
    </div>
    <div class="panel-body">
        <p>
            <?php echo $this->escapeHtml($this->getCustomer()->getName()) ?><br />
            <?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?><br />
            <a href="<?php echo $this->getChangePasswordUrl() ?>"><?php echo $this->__('Change Password') ?></a>
        </p>
    </div>
</div>

<?php if( $this->isNewsletterEnabled() ): ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <a href="<?php echo $this->getUrl('newsletter/manage') ?>"
               title="<?php echo $this->__('Edit') ?> <?php echo $this->__('Newsletters') ?>">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <?php echo $this->__('Newsletters') ?>
            </a>
        </div>
        <div class="panel-body">
            <p>
                <?php if( $this->getIsSubscribed() ): ?>
                    <?php echo $this->__("You are currently subscribed to 'General Subscription'.") ?>
                <?php else: ?>
                    <?php echo $this->__('You are currently not subscribed to any newsletter.') ?>
                <?php endif; ?>
            </p>
        </div>
    </div>
    <?php /* Extensions placeholder */ ?>
    <?php echo $this->getChildHtml('customer.account.dashboard.info.extra')?>
<?php endif; ?>

